// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// row_overlap
LogicalVector row_overlap(NumericVector row_in, NumericMatrix boxes);
RcppExport SEXP tagcloud_row_overlap(SEXP row_inSEXP, SEXP boxesSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type row_in(row_inSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type boxes(boxesSEXP);
    __result = Rcpp::wrap(row_overlap(row_in, boxes));
    return __result;
END_RCPP
}
// any_overlap
LogicalVector any_overlap(NumericMatrix boxes);
RcppExport SEXP tagcloud_any_overlap(SEXP boxesSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericMatrix >::type boxes(boxesSEXP);
    __result = Rcpp::wrap(any_overlap(boxes));
    return __result;
END_RCPP
}
// is_overlap
LogicalVector is_overlap(NumericVector box, NumericMatrix boxes);
RcppExport SEXP tagcloud_is_overlap(SEXP boxSEXP, SEXP boxesSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type box(boxSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type boxes(boxesSEXP);
    __result = Rcpp::wrap(is_overlap(box, boxes));
    return __result;
END_RCPP
}
// spiral
NumericVector spiral(List params, NumericMatrix boxes);
RcppExport SEXP tagcloud_spiral(SEXP paramsSEXP, SEXP boxesSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< List >::type params(paramsSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type boxes(boxesSEXP);
    __result = Rcpp::wrap(spiral(params, boxes));
    return __result;
END_RCPP
}
// ulam
NumericVector ulam(List params, NumericMatrix boxes);
RcppExport SEXP tagcloud_ulam(SEXP paramsSEXP, SEXP boxesSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< List >::type params(paramsSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type boxes(boxesSEXP);
    __result = Rcpp::wrap(ulam(params, boxes));
    return __result;
END_RCPP
}
